<?php
require_once '../../config/database.php';
require_once '../../includes/auth.php';

redirectIfNotLoggedIn();

// Set header untuk file Excel
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="Jadwal_Kuliah_'.date('Y-m-d').'.xls"');
header('Pragma: no-cache');
header('Expires: 0');

// Ambil data jadwal
$stmt = $pdo->prepare("SELECT 
                        j.hari, 
                        TIME_FORMAT(j.jam_mulai, '%H:%i') as jam_mulai,
                        TIME_FORMAT(j.jam_selesai, '%H:%i') as jam_selesai,
                        mk.nama_mk, 
                        mk.kode_mk, 
                        mk.dosen, 
                        mk.sks, 
                        mk.ruangan 
                      FROM jadwal_kuliah j
                      JOIN mata_kuliah mk ON j.mk_id = mk.id
                      WHERE mk.user_id = ?
                      ORDER BY 
                        FIELD(j.hari, 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'),
                        j.jam_mulai");
$stmt->execute([$_SESSION['user_id']]);
$jadwal = $stmt->fetchAll(PDO::FETCH_ASSOC);

$userData = getUserData($pdo, $_SESSION['user_id']);

// Buat tabel HTML untuk Excel
echo '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Jadwal Kuliah</title>
    <style>
        body {
            font-family: "Segoe UI", Arial, sans-serif;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid #2c3e50;
        }
        .header h2 {
            color: #2c3e50;
            font-size: 24px;
            margin-bottom: 5px;
        }
        .header p {
            color: #7f8c8d;
            margin: 3px 0;
            font-size: 14px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            font-size: 12px;
        }
        th {
            background-color: #3498db;
            color: white;
            font-weight: 600;
            text-align: center;
            padding: 10px 8px;
            border: 1px solid #2980b9;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        tr:hover {
            background-color: #f1f8fe;
        }
        .text-center {
            text-align: center;
        }
        .duration-col {
            background-color: #f1f8fe;
            font-weight: bold;
            color: #2c3e50;
        }
        .footer {
            margin-top: 20px;
            font-size: 11px;
            color: #7f8c8d;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>JADWAL PERKULIAHAN</h2>
        <p>Nama: '.htmlspecialchars($userData['nama_lengkap']).'</p>
        <p>NIM: '.htmlspecialchars($userData['nim'] ?? '-').'</p>
        <p>Program Studi: '.htmlspecialchars($userData['prodi'] ?? '-').'</p>
        <p>Semester: '.htmlspecialchars($userData['semester'] ?? '-').'</p>
        <p>Tanggal Export: '.date('d F Y H:i').'</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="10%">Hari</th>
                <th width="10%">Jam Mulai</th>
                <th width="10%">Jam Selesai</th>
                <th width="25%">Mata Kuliah</th>
                <th width="10%">Kode MK</th>
                <th width="5%">SKS</th>
                <th width="15%">Dosen Pengampu</th>
                <th width="10%">Ruangan</th>
            </tr>
        </thead>
        <tbody>';

$no = 1;
foreach ($jadwal as $j) {
    echo '<tr>
            <td class="text-center">'.$no++.'</td>
            <td class="text-center">'.$j['hari'].'</td>
            <td class="text-center">'.$j['jam_mulai'].'</td>
            <td class="text-center">'.$j['jam_selesai'].'</td>
            <td>'.htmlspecialchars($j['nama_mk']).'</td>
            <td class="text-center">'.htmlspecialchars($j['kode_mk']).'</td>
            <td class="text-center">'.$j['sks'].'</td>
            <td>'.htmlspecialchars($j['dosen']).'</td>
            <td class="text-center">'.htmlspecialchars($j['ruangan']).'</td>
          </tr>';
}

echo '</tbody>
    </table>
    
    <div class="footer">
        Generated by SI-NDO - Sistem Informasi Dan Pengingat Mahasiswa | '.date('Y').'
    </div>
</body>
</html>';
exit();
